### ISSUE TITLE
question about PGA usage

### ISSUE THREAD

**Issue by xiongqian123456789** [quxiaojian/PGA#3]
DESCRIPTION
   Application to create BLAST databases, version 2.2.31+

Use '-help' to print detailed descriptions of command line arguments
========================================================================

Error: Unknown argument: "blastdb_version"
BLAST Database error: No alias or index file found for nucleotide database [/home/u4244/choloraplast/test/BN3.chlor.target] in search path [/home/u4244/choloraplast::]
BLAST Database error: No alias or index file found for nucleotide database [/home/u4244/choloraplast/test/BN3.chlor.target] in search path [/home/u4244/choloraplast::]
BLAST Database error: No alias or index file found for nucleotide database [/home/u4244/choloraplast/test/BN3.chlor.target] in search path [/home/u4244/choloraplast::]
BLAST Database error: No alias or index file found for nucleotide database [/home/u4244/choloraplast/test/BN3.chlor.target] in search path [/home/u4244/choloraplast::]
Error: Unknown argument: "blastdb_version"
BLAST Database error: No alias or index file found for nucleotide database [fasta_temp] in search path [/home/u4244/choloraplast::]

**Comment by quxiaojian** [comment]
Please reinstall your local blast to latest version (blast 2.10.0), and 2.5.0+ or higher is also ok, but blast 2.2.31+ is a little old. Then make sure that blast is in your environmental path. You can check blast version by inputing "blastn -version". Hope it can help.

**Comment by quxiaojian** [comment]
Latest blastn has updated default value for one parameter, we have made adjustation.
