### ISSUE TITLE
Unconventional use of PGA

### ISSUE THREAD

**Issue by NowickiLab** [quxiaojian/PGA#4]
Hello Xiao-Jian, 

Is it possible to use PGA for annotating mitochondrial genomes - by simply replacing the database of annotated genomes with mitochondrial .gb(s)?

**Comment by quxiaojian** [comment]
> 
Hi Nowicki,
No, because some genes in mito genomes have more exons than in plastomes. We have not consider mito genomes when develop this method.
Xiao-Jian
