### ISSUE TITLE
程序报错

### ISSUE THREAD

**Issue by ysy12306** [quxiaojian/PGA#6]
我运行的每组数据都会出现
“substr outside of string at PGA.pl line 5475.
substr outside of string at PGA.pl line 7831.”的提示，请问这是程序存在问题吗，是否会影响结果

**Comment by quxiaojian** [comment]
> 我运行的每组数据都会出现 “substr outside of string at PGA.pl line 5475. substr outside of string at PGA.pl line 7831.”的提示，请问这是程序存在问题吗，是否会影响结果

示例也会出现这个吗？

**Comment by ysy12306** [comment]
示例不会，我分析的是拟南芥叶绿体，运行后警告中还有这些信息：
Warning: trnA (positive one-intron PCG) intron-exon boundary need to be checked!
Warning: trnG (positive one-intron PCG) has non-canonical start codon and intron-exon boundary need to be checked!
Warning: trnI (positive one-intron PCG) intron-exon boundary need to be checked!
Warning: trnK (negative one-intron PCG) has non-canonical start codon and intron-exon boundary need to be checked!
Warning: trnL (positive one-intron PCG) intron-exon boundary need to be checked!
Total number of genes in the reference plastome(s): 131.
Total number of genes annotated in the target plastome: 112.
All gene names from the reference plastome(s) that were not annotated in the target plastome:
trnW	trnD	trnM	trnfM	rrn5S	trnN	trnP	trnY	trnE	trnF	trnQ	trnS	trnT	rrn23S	rrn16S	trnH	trnC	rrn5s	rrn4.5S

**Comment by quxiaojian** [comment]
不要随意改变参考，用无油樟即可。如果想用其它物种作为参考，请先用无油樟作为参考注释其它物种，保证参考的准确性。

**Comment by quxiaojian** [comment]
> 示例不会，我分析的是拟南芥叶绿体，运行后警告中还有这些信息： Warning: trnA (positive one-intron PCG) intron-exon boundary need to be checked! Warning: trnG (positive one-intron PCG) has non-canonical start codon and intron-exon boundary need to be checked! Warning: trnI (positive one-intron PCG) intron-exon boundary need to be checked! Warning: trnK (negative one-intron PCG) has non-canonical start codon and intron-exon boundary need to be checked! Warning: trnL (positive one-intron PCG) intron-exon boundary need to be checked! Total number of genes in the reference plastome(s): 131. Total number of genes annotated in the target plastome: 112. All gene names from the reference plastome(s) that were not annotated in the target plastome: trnW trnD trnM trnfM rrn5S trnN trnP trnY trnE trnF trnQ trnS trnT rrn23S rrn16S trnH trnC rrn5s rrn4.5S

不要随意改变参考，用无油樟即可。如果想用其它物种作为参考，请先用无油樟作为参考注释其它物种，保证参考的准确性
